name: ci

on:
  push:
    branches: [main, "release-**"]
  pull_request:
  workflow_dispatch:

# The CACHE_VERSION can be updated to force the use of a new cache if
# the current cache contents become corrupted/invalid.  This can
# sometimes happen when (for example) the OS version is changed but
# older .so files are cached, which can have various effects
# (e.g. cabal complains it can't find a valid version of the "happy"
# tool).
env:
  NAME: czz
  CACHE_VERSION: 1

jobs:

  lint:
    name: hlint
    runs-on: ubuntu-latest
    env:
      HLINT_VERSION: 3.4

    steps:
    - uses: actions/checkout@v3

    - name: cache
      uses: actions/cache@v3
      with:
        path: ./hlint-${HLINT_VERSION}/hlint
        key: |
          hlint-${{ env.HLINT_VERSION }}

    - name: prep
      shell: bash
      run: |
        curl --location -o hlint.tar.gz \
          https://github.com/ndmitchell/hlint/releases/download/v${HLINT_VERSION}/hlint-${HLINT_VERSION}-x86_64-linux.tar.gz
        tar xvf hlint.tar.gz

    - name: lint
      shell: bash
      run: >
        ./hlint-${HLINT_VERSION}/hlint
        czz/src
        czz-jvm/{exe,src,test}
        czz-llvm/{exe,src,test}
        czz-llvm-tui/{exe,src}

  build:
    name: ${{ matrix.os }} GHC-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: [9.2.1]
        allow-failure: [false]
      fail-fast: true

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v1
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: false

    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.setup-haskell.outputs.cabal-store }}
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: |
          cabal-${{ env.CACHE_VERSION }}-${{ runner.os }}-ghc${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}-${{ github.ref }}
        restore-keys: |
          cabal-${{ env.CACHE_VERSION }}-${{ runner.os }}-ghc${{ matrix.ghc }}-
          cabal-${{ env.CACHE_VERSION }}-${{ runner.os }}-ghc${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}-

    - name: prep
      shell: bash
      # TODO(lb): cabal check
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks all

    - name: build
      shell: bash
      run: cabal build all

    - name: test
      shell: bash
      run: |
        sudo apt-get install -y llvm z3
        cabal test czz-llvm

    # TODO(#52)

    # - name: doc
    #   shell: bash
    #   run: cabal haddock all

    - name: build bdist
      shell: bash
      run: |
        ./scripts/dist.sh czz-llvm-tui
      env:
        OS_TAG: ${{ matrix.os }}

    - name: upload bdist
      uses: actions/upload-artifact@v3
      if: github.repository == 'langston-barrett/czz'
      with:
        name: "${{ env.NAME }}-bdist-${{ matrix.os }}"
        path: "*.tar.gz"
        if-no-files-found: error

    - name: doc
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"

    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/build/html

